version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT:/var/www/html/public
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: healthcare-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

